### ISSUE TITLE
Runs really slow now....

### ISSUE THREAD

**Issue by mepland** [dougphy/PHY505_B2b#1]
Maybe making the SD the whole target is a bad idea? Hopefully it's just being slow because it's drawing it, sys time was .72s/event while real time was 42s/event - see screenshot.

![screenshot from 2015-01-26 18 22 00](https://cloud.githubusercontent.com/assets/4729931/5910588/b57b7080-a589-11e4-9c34-56db5ea8ce6e.png)

**Comment by dougphy** [comment]
Yep it's the drawing that's taking a while. 500 events took < 5 seconds when running the non-visual macro:
./exampleB2b run2.mac
